Add stdalign.h and stdnoreturn.h.
CHERIoT-Platform/cheriot-rtos pull request #295
Opened 2024-09-04 09:14 UTC by davidchisnall

These were added in C11 and removed in C23.  The implementations are no-ops in C++ and C >= C23 modes.

2024-09-04 09:15 UTC, davidchisnall commented
@sleffler

2024-09-05 02:20 UTC, nwf requested changes
Typos

2024-09-05 02:20 UTC, nwf commented on sdk/include/stdnoreturn.h
> + * C++-compatible spelling for `_Alisnas`.
```suggestion
 * C++-compatible spelling for `_Noreturn`.
```

2024-09-05 02:20 UTC, nwf commented on sdk/include/stdalign.h
> + * C++-compatible spelling for `_Alisnas`.
```suggestion
 * C++-compatible spelling for `_Alignas`.
```

2024-09-05 02:20 UTC, nwf commented on sdk/include/stdalign.h
> + * C++-compatible spelling for `_Alisnof`.
```suggestion
 * C++-compatible spelling for `_Alignof`.
```

2024-09-05 07:54 UTC, nwf approved these changes
LGTM

2024-09-05 08:05 UTC, merged