Sonata Pinmux driver
CHERIoT-Platform/cheriot-rtos pull request #360
Opened 2024-11-27 10:04 UTC by HU90m

A driver for Sonata v1.0's Pinmux

2024-11-27 10:58 UTC, marnovandermaas approved these changes
Thanks Hugo, this looks correct to me from a code review.

2024-11-28 08:43 UTC, HU90m commented
I think in the case of the Pinmux it's best to make sure sink names match the canonical name used documentation, RTL and schematic. The sinks are enum classes, so breaking the code style shouldn't cause much confusion here.

2024-12-02 16:56 UTC, nwf requested changes
It looks like platform-pinmux.hh is generated from [sonata-system's platform-pinmux.hh.tpl](https://github.com/lowRISC/sonata-system/blob/658a74130ba8436c4a5619671b7cace2179d6ce4/sw/cheri/common/platform-pinmux.hh.tpl) via its [top_gen](https://github.com/lowRISC/sonata-system/blob/658a74130ba8436c4a5619671b7cace2179d6ce4/util/top_gen/generator.py).  It'd be good to...
- have a comment to that effect in the file
- update the `.hh.tpl` in light of the changes made here (`NOLINT`, names of some function arguments and locals, &c).

FWIW, I ran `git diff --word-diff` having clobbered `sonata-system` `v0.3-403-g658a741`'s `sw/cheri/common/platform-pinmux.hh` with the one from this PR; that might be the easiest way to find the requisite changes to the template?

I have not attempted to validate that `top_gen` is consistent between the RTL and C++ it generates, much preferring to merely assume so. :)

2025-01-06 12:02 UTC, HU90m commented
↑ rebased onto main, ↓ added comment pointing to what generates the file.

*See https://github.com/lowRISC/sonata-system/pull/376*

2025-01-06 18:42 UTC, nwf commented
Thanks for doing that.  One nit aside, this LGTM.

2025-01-06 22:40 UTC, nwf commented
Want to update the `platform-pinmux.hh` herein with the result of that PR?  I think it's good to go after that.

2025-01-07 13:40 UTC, HU90m commented
> Want to update the `platform-pinmux.hh` herein with the result of that PR? I think it's good to go after that.

The `sonata-system` repo uses the lowRISC C++ formatting, *unlike `sonata-software`*, so the output of the topgen script has to be lowRISC formatted.

This PR has already been updated with the updated with the latest output, only run through clang-format with the CHERIoT settings.

2025-01-07 18:03 UTC, merged

2025-01-23 10:44 UTC, davidchisnall commented
I missed in review, but this seems to have an Apache license.  Is it possible to relicense to match the rest of the repository?